version: "2.2"
services:
  overleaf:
    restart: always
    image: ldap-overleaf-sl:5.0.6
    container_name: ldap-overleaf-sl
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      autossh:
        condition: service_started
    privileged: false
    ports:
      - ${LOCALHOST}:${LOCALPORT}:80
    links:
      - mongo
      - redis
      - git-bridge
      - autossh
    environment:
      GIT_BRIDGE_ENABLED: true
      GIT_BRIDGE_HOST: "git-bridge"
      GIT_BRIDGE_PORT: "8000"
      V1_HISTORY_URL: "http://overleaf:3100/api"
    volumes:
      - ${MYDATA}/overleaf:/var/lib/overleaf
    environment:
      OVERLEAF_APP_NAME: Overleaf
      OVERLEAF_MONGO_URL: mongodb://mongo/overleaf
      OVERLEAF_SITE_URL: https://${MYDOMAIN}
      OVERLEAF_NAV_TITLE: Overleaf - run by ${MYDOMAIN}
      #OVERLEAF_HEADER_IMAGE_URL: https://${MYDOMAIN}/logo.svg
      OVERLEAF_ADMIN_EMAIL: ${MYMAIL}
      OVERLEAF_LEFT_FOOTER: '[{"text": "Self-hosted instance} ]'
      OVERLEAF_RIGHT_FOOTER: '[{"text": "<a href=\"https://github.com/smhaller/ldap-overleaf-sl\">OAuth2 Overleaf Community Edition</a>"} ]'
      OVERLEAF_EMAIL_FROM_ADDRESS: "noreply@${MYDOMAIN}"
      # OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID:
      # OVERLEAF_EMAIL_AWS_SES_SECRET_KEY:
      OVERLEAF_EMAIL_SMTP_HOST: smtp.${MYDOMAIN}
      OVERLEAF_EMAIL_SMTP_PORT: 587
      OVERLEAF_EMAIL_SMTP_SECURE: "false"
      # OVERLEAF_EMAIL_SMTP_USER:
      # OVERLEAF_EMAIL_SMTP_PASS:
      # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
      # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
      OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by ${MYDOMAIN} - please contact ${MYMAIL} if you experience any issues."

      # make public links accessible w/o login (link sharing issue)
      # https://github.com/overleaf/docker-image/issues/66
      # https://github.com/overleaf/overleaf/issues/628
      # https://github.com/overleaf/web/issues/367
      # Fixed in 2.0.2 (Release date: 2019-11-26)
      OVERLEAF_ALLOW_PUBLIC_ACCESS: "true"
      OVERLEAF_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: "true"

      # Uncomment the following line to enable secure cookies if you are using SSL
      # OVERLEAF_SECURE_COOKIE: "true"
      OVERLEAF_BEHIND_PROXY: "true"

      LDAP_SERVER: ldaps://LDAPSERVER:636
      LDAP_BASE: ou=people,dc=DOMAIN,dc=TLD

      ### There are to ways get users from the ldap server

      ## NO LDAP BIND USER:
      # Tries directly to bind with the login user (as uid)
      # LDAP_BINDDN: uid=%u,ou=someunit,ou=people,dc=DOMAIN,dc=TLD

      ## Or you can use ai global LDAP_BIND_USER
      # LDAP_BIND_USER:
      # LDAP_BIND_PW:

      # Only allow users matching LDAP_USER_FILTER
      LDAP_USER_FILTER: "(memberof=cn=GROUPNAME,ou=groups,dc=DOMAIN,dc=TLD)"

      # If user is in ADMIN_GROUP on user creation (first login) isAdmin is set to true.
      # Admin Users can invite external (non ldap) users. This feature makes only sense
      # when ALLOW_EMAIL_LOGIN is set to 'true'. Additionally admins can send
      # system wide messages.
      LDAP_ADMIN_GROUP_FILTER: "(memberof=cn=ADMINGROUPNAME,ou=groups,dc=DOMAIN,dc=TLD)"
      ALLOW_EMAIL_LOGIN: "false"

      # All users in the LDAP_CONTACT_FILTER are loaded from the ldap server into contacts.
      LDAP_CONTACT_FILTER: "(memberof=cn=GROUPNAME,ou=groups,dc=DOMAIN,dc=TLD)"
      LDAP_CONTACTS: "false"

      ## OAuth2 Settings
      OAUTH2_ENABLED: "true"
      OAUTH2_PROVIDER: https://github.com
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      OAUTH2_SCOPE: public
      OAUTH2_AUTHORIZATION_URL: https://github.com/login/oauth/authorize
      OAUTH2_TOKEN_URL: https://github.com/login/oauth/access_token
      OAUTH2_TOKEN_CONTENT_TYPE: "application/x-www-form-urlencoded"
      OAUTH2_PROFILE_URL: https://api.github.com/user
      OAUTH2_USER_ATTR_EMAIL: email
      OAUTH2_USER_ATTR_UID: id
      OAUTH2_USER_ATTR_FIRSTNAME: name
      OAUTH2_USER_ATTR_LASTNAME:
      OAUTH2_USER_ATTR_IS_ADMIN: site_admin

      # Same property, unfortunately with different names in
      # different locations
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      ENABLED_LINKED_FILE_TYPES: "url,project_file"

      # Enables Thumbnail generation using ImageMagick
      ENABLE_CONVERSIONS: "true"

  mongo:
    restart: always
    image: mongo:5.0
    container_name: mongo
    expose:
      - 27017
    volumes:
      - ${MYDATA}/mongo_data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    command: "--replSet overleaf"

  # See also: https://github.com/overleaf/overleaf/issues/1120
  mongoinit:
    image: mongo:5.0
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint:
      [
        "mongo",
        "--host",
        "mongo:27017",
        "--eval",
        'rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })',
      ]

  redis:
    restart: always
    image: redis:6.2
    container_name: redis
    expose:
      - 6379
    volumes:
      - ${MYDATA}/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  git-bridge:
    restart: always
    image: quay.io/sharelatex/git-bridge:5.0.6 # tag should match the `sharelatex` container tag
    volumes:
        - ${MYDATA}/git_bridge_data:/data/git-bridge
    container_name: git-bridge
    expose:
        - "8000"
    environment:
        GIT_BRIDGE_API_BASE_URL: "http://overleaf:3000/api/v0/"
        GIT_BRIDGE_OAUTH2_SERVER: "http://overleaf"
        GIT_BRIDGE_POSTBACK_BASE_URL: "http://git-bridge:8000"
        GIT_BRIDGE_ROOT_DIR: "/data/git-bridge"
    user: root
    command: ["/server-pro-start.sh"]

  autossh:
    image: autossh
    environment:
      - SSH_REMOTE_USER=${SSH_REMOTE_USER}
      - SSH_REMOTE_HOST=${SSH_REMOTE_HOST}
      - SSH_REMOTE_PORT=${SSH_REMOTE_PORT}
      - SSH_TARGET_HOST=${LOCALHOST}
      - SSH_TARGET_PORT=${LOCALPORT}
      - SSH_TUNNEL_PORT=${SSH_TUNNEL_PORT}
      - SSH_OPTIONS=-o ConnectTimeout=10 -o StreamLocalBindUnlink=yes -o UseRoaming=no
      - TUNNEL_SECRET=
      - TUNNEL_REMOTE_ID=
    restart: always
    volumes:
      - ${PWD}/id_rsa:/id_rsa
